# TCL File Generated by Component Editor 15.0
# Wed Oct 28 23:16:42 GMT 2015
# DO NOT MODIFY


# 
# ButtonsCtrl "ButtonsCtrl" v1.0
#  2015.10.28.23:16:42
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module ButtonsCtrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME ButtonsCtrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ButtonsCtrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL shiftregctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file shiftregctl.sv SYSTEM_VERILOG PATH shiftregctl.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point shiftreg_out
# 
add_interface shiftreg_out conduit end
set_interface_property shiftreg_out associatedClock clock
set_interface_property shiftreg_out associatedReset reset
set_interface_property shiftreg_out ENABLED true
set_interface_property shiftreg_out EXPORT_OF ""
set_interface_property shiftreg_out PORT_NAME_MAP ""
set_interface_property shiftreg_out CMSIS_SVD_VARIABLES ""
set_interface_property shiftreg_out SVD_ADDRESS_GROUP ""

add_interface_port shiftreg_out shiftreg_loadn shiftreg_loadn Output 1
add_interface_port shiftreg_out shiftreg_clk shiftreg_clk Output 1


# 
# connection point shiftreg_in
# 
add_interface shiftreg_in conduit end
set_interface_property shiftreg_in associatedClock clock
set_interface_property shiftreg_in associatedReset reset
set_interface_property shiftreg_in ENABLED true
set_interface_property shiftreg_in EXPORT_OF ""
set_interface_property shiftreg_in PORT_NAME_MAP ""
set_interface_property shiftreg_in CMSIS_SVD_VARIABLES ""
set_interface_property shiftreg_in SVD_ADDRESS_GROUP ""

add_interface_port shiftreg_in shiftreg_out shiftreg_in Input 1


# 
# connection point buttons
# 
add_interface buttons conduit end
set_interface_property buttons associatedClock ""
set_interface_property buttons associatedReset ""
set_interface_property buttons ENABLED true
set_interface_property buttons EXPORT_OF ""
set_interface_property buttons PORT_NAME_MAP ""
set_interface_property buttons CMSIS_SVD_VARIABLES ""
set_interface_property buttons SVD_ADDRESS_GROUP ""

add_interface_port buttons buttons export Output 16


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_50m clk Input 1

