#ifndef GPU_WORKQUEUE_IOCTL_H
#define GPU_WORKQUEUE_IOCTL_H

#define WORKQUEUE_IOCTL_TYPE 124
#define IOCTL_WORKQUEUE_GET_NUM_CORES _IO(WORKQUEUE_IOCTL_TYPE, 1)

#endif /* GPU_WORKQUEUE_IOCTL_H */