hardware:
	gcc triangles.c draw.c workqueue.c pixelstream_palette.c -lrt -O3 -Wall -DHARDWARE_RENDER

software:
	gcc triangles.c draw.c workqueue.c pixelstream_palette.c  -lrt -O3

clean:
	rm a.out
