#ifndef PIXELSTREAM_PALETTE_IOCTL_H
#define PIXELSTREAM_PALETTE_IOCTL_H

#define IOCTL_TYPE 123
#define IOCTL_PALETTE_SET_COLOR _IOW(IOCTL_TYPE, 1, unsigned int)
#define IOCTL_PIXELSTREAM_SET_BUFFER _IOW(IOCTL_TYPE, 2, unsigned int)
#define IOCTL_PIXELSTREAM_GET_BUFFER _IO(IOCTL_TYPE, 3)

#endif /* PIXELSTREAM_PALETTE_IOCTL_H */