#ifndef PIXELSTREAM_PALETTE_IOCTL_H
#define PIXELSTREAM_PALETTE_IOCTL_H

#define PIXELSTREAM_IOCTL_TYPE 123
#define IOCTL_PALETTE_SET_COLOR _IOW(PIXELSTREAM_IOCTL_TYPE, 1, unsigned int)
#define IOCTL_PIXELSTREAM_SET_BUFFER _IOW(PIXELSTREAM_IOCTL_TYPE, 2, unsigned int)
#define IOCTL_PIXELSTREAM_GET_BUFFER _IO(PIXELSTREAM_IOCTL_TYPE, 3)

#endif /* PIXELSTREAM_PALETTE_IOCTL_H */